using System.Collections.Generic;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Rendering.Universal;
using UnityEngine.Tilemaps;
using GolemFactory.World;

namespace GolemFactory.Editor
{
    // Builds the whole workshop shell of the active scene: repaints the floor Tilemap to
    // FloorLayout's current HalfExtent, walls the north edge head-on and caps the east and west
    // edges, skirts the open south edge, caps the two north corners with posts, and scatters
    // crates/barrels along the walls.
    // Reruns cleanly and deterministically -- every piece is found by name and updated in place,
    // and every placement comes from FloorTileVariant / FloorLayout rather than a random
    // scatter, so regenerating never produces scene churn.
    //
    // Everything is built as plain GameObjects rather than prefab instances. Seven distinct
    // piece types (north wall, its lamp variant, the east and west caps, skirting, posts, two
    // props) would otherwise mean seven prefabs to keep in sync with this one code path, and the
    // pieces are pure decoration with no per-instance authoring -- one generator is the simpler
    // contract.
    public static class SandboxFloorGenerator
    {
        private const string ArtRoot = "Assets/_Project/Art/";
        private const string TileRoot = "Assets/_Project/Tilemaps/";
        private const string LitSpriteMaterialPath = "Assets/Settings/SpriteLit2D.mat";

        private const string WallsParentName = "Walls";
        private const string PropsParentName = "Props";

        // Every scene carrying a workshop floor. Both have a Grid; Main is the milestone-demo
        // scene and Sandbox the playable one, and they share the environment art, so a pass that
        // rebuilt only one would leave the other on the previous projection's geometry.
        private static readonly string[] FloorScenePaths =
        {
            "Assets/_Project/Scenes/Main.unity",
            "Assets/_Project/Scenes/Sandbox.unity",
        };

        // Sprite name -> the Tile asset built from it. Index order must match FloorTileVariant:
        // 0..3 plank variants, 4 brass plate, 5 grate.
        private static readonly string[] FloorSpriteNames =
        {
            "floor_tile", "floor_tile_wood_b", "floor_tile_wood_c", "floor_tile_wood_d",
            "floor_tile_accent", "floor_tile_grate",
        };

        private static readonly string[] FloorTileAssetNames =
        {
            "FloorTile", "FloorTileWoodB", "FloorTileWoodC", "FloorTileWoodD",
            "FloorTileAccent", "FloorTileGrate",
        };

        // The market street's paving, kept as its own pair rather than appended to the floor set
        // above: FloorTileVariant indexes into that array by position, so a seventh entry would
        // silently become a rare workshop accent tile. The street picks between these two by its
        // own rule instead.
        private static readonly string[] StreetSpriteNames = { "street_cobble", "street_cobble_b" };
        private static readonly string[] StreetTileAssetNames = { "StreetCobble", "StreetCobbleB" };

        // Square, centre-pivoted, one cell -- regenerated by the top-down pass but placed by
        // other systems (the build ghost by BuildModeController, the ring by PlayerInteractor,
        // the belt surface by the belt visuals), so they never appear in the pivot table and
        // this sweep used to miss them entirely. They are the sprites that follow the cursor and
        // the player, i.e. the ones a player looks at most; left at the isometric PPU they render
        // at half a cell, and a half-size build ghost mis-sells every placement in the game.
        private static readonly string[] CentrePivotOverlayNames =
        {
            "build_ghost_tile", "interaction_ring", "belt_tile",
            // The market street's paving. Same treatment as the floor tiles it sits beside: one
            // cell, centre-pivoted, PPU 64.
            "street_cobble", "street_cobble_b",
        };

        // TOP-DOWN: every environment sprite is authored at 64 art pixels per world unit, so a
        // 64x64 floor tile is exactly one 1 x 1 cell. This was PPU 128 for the isometric run,
        // where the art was authored at 32 px/unit and upscaled x4 to make a 128x64 diamond fill
        // a 1 x 0.5 cell. Leaving it at 128 after the projection switch renders every new square
        // tile at half a cell, which is a floor of quarter-size tiles with gaps between them.
        private const float EnvironmentPixelsPerUnit = 64f;

        // Custom pivots, all normalized from the bottom-left. THE RULE, uniform across the set:
        // the pivot is the piece's CONTACT LINE WITH THE FLOOR -- the base of the body, excluding
        // the contact shadow the art draws beneath it, so the shadow falls on the floor in front
        // rather than lifting the piece off it. That point has to land exactly on the
        // FloorLayout.GetEdgeAnchor position for consecutive segments to butt together.
        //
        // Every value below is derived from the canvas geometry in
        // Tools/Art/generate_topdown_environment.py and must be updated with it. The
        // fractions are written unreduced (3f / 96f, not 0.03125f) so they stay legible as
        // "3 shadow rows out of a 96px canvas".
        private static readonly Dictionary<string, Vector2> EnvironmentPivots = new Dictionary<string, Vector2>
        {
            // Head-on wall, 64x96, three shadow rows at the foot. Used on the north edge.
            // The _ne pair is the same image (see make_wall) and is currently unplaced; it is
            // kept in this table so it imports consistently if anything ever wires it.
            { "wall_segment_ne", new Vector2(0.5f, 3f / 96f) },
            { "wall_segment_ne_lamp", new Vector2(0.5f, 3f / 96f) },
            { "wall_segment_nw", new Vector2(0.5f, 3f / 96f) },
            { "wall_segment_nw_lamp", new Vector2(0.5f, 3f / 96f) },
            // Side walls, 40x64, running along Y. The contact line is VERTICAL here, not
            // horizontal, so it is the x that is pinned to the boundary and the y that centres
            // on the cell. The three shadow columns sit inboard of the line, on the floor.
            // The west entry is the mirror: FLIP_LEFT_RIGHT maps pixel boundary p to 40 - p,
            // so a body starting at boundary 3 ends at boundary 37.
            { "wall_side_e", new Vector2(3f / 40f, 0.5f) },
            { "wall_side_w", new Vector2(37f / 40f, 0.5f) },
            // Skirting band, 64x24, hangs entirely BELOW the floor's south edge -- so the
            // contact line is the top of the canvas, not the bottom.
            { "floor_edge_se", new Vector2(0.5f, 1f) },
            { "floor_edge_sw", new Vector2(0.5f, 1f) },
            // The street's far kerb, 64x24. Same geometry and same top-of-canvas pivot as the
            // joist face above, and a separate sprite for the reason make_street_edge records:
            // floor_edge_sw is timber on the plank palette, which is right where the raised
            // shop floor stops and wrong as the edge of a stone road.
            { "street_edge", new Vector2(0.5f, 1f) },
            { "wall_corner_post", new Vector2(0.5f, 1f / 96f) },
            { "prop_crate", new Vector2(0.5f, 1f / 56f) },
            { "prop_barrel", new Vector2(0.5f, 1f / 56f) },
            { "ground_shadow", new Vector2(0.5f, 0.5f) },
            // Market carts, 96x120 with three shadow rows at the foot -- the same contact-line
            // rule the walls follow, so a cart stands on its cell rather than hovering over it.
            // WIDER THAN THEIR CELL ON PURPOSE: a cart occupies one cell and the sprite overhangs
            // it by 16px each side, exactly as a wall segment overhangs its boundary. The street
            // lays them on a two-cell pitch, which keeps the overhang clear of the neighbour and
            // leaves the two approach tiles §3.2's extractor cap needs.
            { "stall_scrap", new Vector2(0.5f, 3f / 120f) },
            { "stall_coal", new Vector2(0.5f, 3f / 120f) },
            { "stall_copper_ore", new Vector2(0.5f, 3f / 120f) },
            { "stall_zinc_ore", new Vector2(0.5f, 3f / 120f) },
            { "stall_aether", new Vector2(0.5f, 3f / 120f) },
        };

        // Wall sconces every fourth segment along the one head-on wall run. Isometric had two
        // lit runs and offset their phases so lamps never bunched at the shared corner; top-down
        // has a single head-on run (the side walls are seen as caps and carry no sconce), so the
        // second phase is gone and the intensity is up to cover a room lit from one edge.
        private const int LampSpacing = 4;
        private static readonly Color LampColor = new Color(1f, 0.72f, 0.42f, 1f);

        // --- The dramatic-lighting pass -----------------------------------------------------
        // TUNING, and they only mean anything as a pair: a lit spot is
        // (Global + Sconce) / Global = 3.4x the shadow between lamps, against 1.8x before.
        // Cutting the ambient is what does the work; raising the sconce alone would just wash
        // the whole room brighter.
        private const float GlobalIntensity = 0.62f;
        private const float SconceIntensity = 1.5f;

        // WHERE THE LIGHT GOES IS NOT WHERE THE FLAME IS PAINTED, and that is not a bug.
        //
        // make_wall paints the sconce glow 68px above the wall's base line (canvas row 24 on a
        // 96px canvas whose base line is 3 rows up), so the obvious value here is 68f/64f. It is
        // wrong. A sprite's vertical offset under top-down is a FAKE ELEVATION: the wall's foot
        // is on the boundary line and its body is drawn rising up-screen, but in WORLD terms all
        // of that is north of the floor. A point light at the painted flame sits a cell and a
        // bit outside the room, putting its full-intensity core on background and reaching the
        // floor with nothing but the tail of the falloff.
        //
        // So the lit pool is placed just inside the room instead, and the glow on the wall face
        // stays painted into the sprite where it already is. The isometric value (1.28) was the
        // same mistake, hidden by a projection where a world unit spanned two cells of depth.
        private const float LampLightInset = -0.25f;

        [MenuItem("Tools/Golem Factory/Generate Floor (with Walls)")]
        public static void GenerateFloorWithWalls()
        {
            Generate(spawnWalls: true);
        }

        [MenuItem("Tools/Golem Factory/Generate Floor (no Walls)")]
        public static void GenerateFloorOnly()
        {
            Generate(spawnWalls: false);
        }

        // Kept as its own menu item rather than folded into Generate: import settings are an
        // asset-wide, one-off concern, and re-applying them forces a texture reimport that is
        // far slower than a repaint.
        [MenuItem("Tools/Golem Factory/Reimport Environment Art")]
        public static void ReimportEnvironmentArt()
        {
            int changed = 0;
            var names = new List<string>(FloorSpriteNames);
            names.AddRange(CentrePivotOverlayNames);
            names.AddRange(EnvironmentPivots.Keys);

            foreach (string spriteName in names)
            {
                string path = ArtRoot + spriteName + ".png";
                var importer = AssetImporter.GetAtPath(path) as TextureImporter;
                if (importer == null)
                {
                    Debug.LogWarning("SandboxFloorGenerator: missing environment texture " + path);
                    continue;
                }

                Vector2 pivot;
                bool custom = EnvironmentPivots.TryGetValue(spriteName, out pivot);

                var settings = new TextureImporterSettings();
                importer.ReadTextureSettings(settings);
                settings.textureType = TextureImporterType.Sprite;
                settings.spriteMode = (int)SpriteImportMode.Single;
                settings.spriteAlignment = (int)(custom ? SpriteAlignment.Custom : SpriteAlignment.Center);
                settings.spritePixelsPerUnit = EnvironmentPixelsPerUnit;
                settings.filterMode = FilterMode.Point;
                settings.mipmapEnabled = false;
                settings.alphaIsTransparency = true;
                if (custom)
                {
                    settings.spritePivot = pivot;
                }
                importer.SetTextureSettings(settings);
                importer.textureCompression = TextureImporterCompression.Uncompressed;
                importer.SaveAndReimport();
                changed++;
            }

            AssetDatabase.Refresh();
            Debug.Log("SandboxFloorGenerator: reimported " + changed + " environment textures at PPU "
                      + EnvironmentPixelsPerUnit + ".");
        }

        // The whole environment pass in one call: reimport the art at the current PPU/pivots,
        // then repaint and re-wall every scene that has a floor. Exists as a static entry point
        // (not just a menu item) so it runs headless via
        //   Unity.exe -batchmode -projectPath . -executeMethod
        //     GolemFactory.Editor.SandboxFloorGenerator.RebuildEnvironmentAllScenes
        // which is the only way to do it while nobody is sitting in front of the Editor, and the
        // reason the projection switch could otherwise only be finished by hand.
        //
        // Idempotent in the sense the rest of the authoring scripts are, and idempotent all the
        // way down to the scene file: every piece is found by name and updated in place (see
        // EnsureChild), every placement is derived from FloorLayout/FloorTileVariant, so a second
        // run leaves `git diff` empty rather than producing a second room OR renumbering the
        // first one.
        [MenuItem("Tools/Golem Factory/Rebuild Environment (All Scenes)")]
        public static void RebuildEnvironmentAllScenes()
        {
            ReimportEnvironmentArt();

            foreach (string scenePath in FloorScenePaths)
            {
                if (AssetDatabase.LoadAssetAtPath<SceneAsset>(scenePath) == null)
                {
                    Debug.LogWarning("SandboxFloorGenerator: no scene at " + scenePath + ", skipping.");
                    continue;
                }

                UnityEngine.SceneManagement.Scene scene =
                    EditorSceneManager.OpenScene(scenePath, OpenSceneMode.Single);

                // SAVE ONLY ON SUCCESS, and say so honestly otherwise. The first version called
                // SaveScene unconditionally and then logged "rebuilt and saved", so a Generate
                // that bailed for a missing Grid or Tilemap reported success and wrote the
                // unmodified scene back to disk. That is exactly the trusting-the-authoring-log
                // failure CLAUDE.md warns about, introduced by the very pass that quotes it.
                if (!Generate(spawnWalls: true))
                {
                    Debug.LogError("SandboxFloorGenerator: FAILED on " + scenePath + " -- not saved.");
                    continue;
                }

                EditorSceneManager.SaveScene(scene);
                Debug.Log("SandboxFloorGenerator: rebuilt and saved " + scenePath);
            }

            AssetDatabase.SaveAssets();
        }

        // Returns false if the scene could not be rebuilt, so the caller can refuse to save it.
        private static bool Generate(bool spawnWalls)
        {
            GameObject gridObject = GameObject.Find("Grid");
            if (gridObject == null)
            {
                Debug.LogError("SandboxFloorGenerator: no 'Grid' GameObject found in the active scene.");
                return false;
            }

            Grid grid = gridObject.GetComponent<Grid>();
            Tilemap tilemap = gridObject.GetComponentInChildren<Tilemap>();
            if (grid == null || tilemap == null)
            {
                Debug.LogError("SandboxFloorGenerator: 'Grid' is missing a Grid and/or child Tilemap component.");
                return false;
            }

            var converter = new GridCoordinateConverter(grid.cellSize);
            TileBase[] tiles = LoadOrCreateFloorTiles();

            // THE TILEMAP AND THE CONVERTER MUST AGREE ON WHERE A CELL IS, and by default they
            // do not. Unity renders tile (x,y) at CellToWorld(cell) + tileAnchor * cellSize, and
            // tileAnchor defaults to (0.5, 0.5) -- so with a 1x1 cell the painted floor sits half
            // a cell up and half a cell right of every position GridCoordinateConverter computes.
            // Walls anchored at +/-12.5 would bisect the outermost tile row on two sides and
            // leave a half-cell gap on the other two, and ClampToFloor would stop the player a
            // full tile short of the painted edge at +X/+Y.
            //
            // Zeroing it puts tile (x,y)'s centre exactly on CellToWorldCenter(x,y). Fixing the
            // TILEMAP rather than the converter is deliberate and follows the architecture: the
            // Tilemap is presentation, the converter is simulation truth (see CLAUDE.md).
            //
            // Isometric masked this -- its anchor offset worked out to (0, +0.25), one axis and
            // half the size, which is small enough to look like art bleed rather than a bug.
            tilemap.tileAnchor = Vector3.zero;

            TileBase[] streetTiles = LoadOrCreateTiles(StreetSpriteNames, StreetTileAssetNames);

            tilemap.ClearAllTiles();
            int tileCount = 0;
            foreach (Vector2Int cell in FloorLayout.GetFloorCells())
            {
                tilemap.SetTile(new Vector3Int(cell.x, cell.y, 0), tiles[FloorTileVariant.Select(cell.x, cell.y)]);
                tileCount++;
            }

            // THE STREET, painted on the same Tilemap as the workshop. One Tilemap, because the
            // two surfaces never overlap (FloorLayout guarantees it, and a test pins it) and a
            // second Tilemap would need its own renderer, sorting order and tileAnchor -- three
            // more things to keep in step for no gain.
            //
            // The variant rule is deliberately NOT FloorTileVariant: that hashes for rare accent
            // tiles (brass plate, grate), which are workshop fittings and would read as debris in
            // the road. Cobbles just alternate on a coprime-ish stride so the two variants
            // interleave without banding.
            int streetCount = 0;
            foreach (Vector2Int cell in FloorLayout.GetStreetCells())
            {
                int variant = Mod(cell.x * 5 + cell.y * 3, streetTiles.Length);
                tilemap.SetTile(new Vector3Int(cell.x, cell.y, 0), streetTiles[variant]);
                streetCount++;
            }

            int pieceCount = 0;
            if (spawnWalls)
            {
                pieceCount = BuildWalls(gridObject.transform, converter) + BuildProps(gridObject.transform, converter);
                TuneGlobalLight();
            }
            else
            {
                // "Floor only" means exactly that, so this path still removes the shell. It is
                // the one place a destroy is the intent rather than a shortcut.
                DestroyChild(gridObject.transform, WallsParentName);
                DestroyChild(gridObject.transform, PropsParentName);
            }

            EditorSceneManager.MarkSceneDirty(gridObject.scene);
            Debug.Log("SandboxFloorGenerator: painted " + tileCount + " floor tiles, "
                      + streetCount + " street tiles, and spawned " + pieceCount
                      + " wall/prop pieces.");
            return true;
        }

        private static int BuildWalls(Transform parent, GridCoordinateConverter converter)
        {
            Transform wallsParent = EnsureChild(parent, WallsParentName);
            var expected = new HashSet<string>();

            Sprite north = LoadSprite("wall_segment_nw");
            Sprite northLamp = LoadSprite("wall_segment_nw_lamp");
            Sprite sideEast = LoadSprite("wall_side_e");
            Sprite sideWest = LoadSprite("wall_side_w");
            Sprite skirt = LoadSprite("floor_edge_sw");
            Sprite kerb = LoadSprite("street_edge");
            Sprite postSprite = LoadSprite("wall_corner_post");

            // WHICH EDGES ARE WALLED IS A TOP-DOWN DECISION, NOT AN INHERITED ONE. Isometric
            // walled the two edges pointing away from the camera and left the two facing it open,
            // because in that projection "away" and "toward" are both diagonals and each covers
            // two compass directions. Flattening the diamond onto the axes breaks that symmetry:
            // the inherited mapping walls north and EAST while leaving south and WEST open, which
            // on screen is a room missing its left wall for no reason the player can see.
            //
            // Top-down wants the standard interior: three walls, and the south edge left open so
            // the camera can see in. North gets the head-on face; east and west get the side
            // caps; south keeps the skirting slab that gives the floor a visible thickness.
            //
            // THE SIDE RUNS FOLLOW THE WORLD, THE SKIRTING FOLLOWS THE ROOM, and the split is
            // the whole of what the street needed. Every run used to walk GetEdgeIndices, i.e.
            // the workshop's own extent -- so once the street existed, the east and west walls
            // stopped dead at the shop front and eight rows of cobbles ran off into background
            // on three sides. Seen in Play mode, that did not read as "outside"; it read as an
            // unfinished tilemap, which is the one thing paving the street was meant to fix.
            //
            // The side walls now run the world's full height (the workshop's neighbours down the
            // road, and the same piece caps the wall's formerly dangling south end for free).
            // The skirting stays on the room's own indices, because it is the plank deck's
            // thickness and has to stop where the planks do.
            int count = 0;
            foreach (int index in FloorLayout.GetWorldEdgeIndices())
            {
                count += PlaceEdgePiece(wallsParent, converter, FloorLayout.Edge.East,
                    index, sideEast, "WallEast", false, expected, world: true);
                count += PlaceEdgePiece(wallsParent, converter, FloorLayout.Edge.West,
                    index, sideWest, "WallWest", false, expected, world: true);
            }

            foreach (int index in FloorLayout.GetEdgeIndices())
            {
                bool lit = Mod(index, LampSpacing) == 0;

                count += PlaceEdgePiece(wallsParent, converter, FloorLayout.Edge.North,
                    index, lit ? northLamp : north, "WallNorth", lit, expected);
                count += PlaceEdgePiece(wallsParent, converter, FloorLayout.Edge.South,
                    index, skirt, "SkirtSouth", false, expected);

            }

            // The far kerb runs the STREET's width, not the room's, since §13.1 widened the road
            // past the building. It used to share the skirting's loop on the reasoning that the
            // two were the same width; they are not any more, and reusing that loop would leave
            // the outer six cells of road at each end unedged -- the exact "unfinished tilemap"
            // read that paving the street was done to fix.
            foreach (int index in FloorLayout.GetStreetEdgeIndices())
            {
                count += PlaceEdgePiece(wallsParent, converter, FloorLayout.Edge.South,
                    index, kerb, "KerbStreet", false, expected, world: true);
            }

            // The two shoulders: the building's south face where it is no longer the world's
            // edge. Head-on wall art, because from the street these are the flanks of the shop
            // rather than a side cap seen edge-on.
            int shoulderIndex = 0;
            foreach (Vector2 anchor in FloorLayout.GetShoulderAnchors())
            {
                string shoulderName = "WallShoulder_" + shoulderIndex;
                EnsureSpriteObject(
                    wallsParent, shoulderName, north, converter.CellFractionToWorld(anchor));
                expected.Add(shoulderName);
                shoulderIndex++;
                count++;
            }

            int postIndex = 0;
            foreach (Vector2 anchor in FloorLayout.GetWallPostAnchors())
            {
                // +1, because a post shares its exact world Y with the north wall segments it
                // caps and overlaps them in X. Equal sorting orders have no defined draw order
                // in Unity, so without the bias which one wins the corner flips between imports.
                Vector3 world = converter.CellFractionToWorld(anchor);
                string name = "WallPost_" + postIndex;
                EnsureSpriteObject(wallsParent, name, postSprite, world, sortingBias: 1);
                expected.Add(name);
                postIndex++;
                count++;
            }

            PruneUnexpected(wallsParent, expected);

            return count;
        }

        // `world` selects which boundary the piece sits on: the workshop's (default) or the
        // world's. They differ only on the south edge, but the flag is passed on the side runs
        // too so the call site says which rectangle it means rather than relying on the reader
        // knowing that east and west happen to coincide.
        private static int PlaceEdgePiece(Transform parent, GridCoordinateConverter converter,
            FloorLayout.Edge edge, int index, Sprite sprite, string namePrefix, bool withLight,
            HashSet<string> expected, bool world = false)
        {
            string name = namePrefix + "_" + index;
            Vector2 anchor = world
                ? FloorLayout.GetWorldEdgeAnchor(edge, index)
                : FloorLayout.GetEdgeAnchor(edge, index);
            Vector3 worldPosition = converter.CellFractionToWorld(anchor);
            GameObject piece = EnsureSpriteObject(parent, name, sprite, worldPosition);
            expected.Add(name);

            // Both directions, because a lamp's segment and a plain segment share a name: retune
            // LampSpacing and a formerly lit segment has to LOSE its light, not keep a stale one.
            EnsureSconceLight(piece.transform, withLight);
            return 1;
        }

        private static int BuildProps(Transform parent, GridCoordinateConverter converter)
        {
            Transform propsParent = EnsureChild(parent, PropsParentName);
            var expected = new HashSet<string>();

            Sprite crate = LoadSprite("prop_crate");
            Sprite barrel = LoadSprite("prop_barrel");
            Sprite shadow = LoadSprite("ground_shadow");

            // Deterministic, irregular-looking clutter hugging all four edges. Each run uses a
            // different phase so the room never looks mirrored, and the interior stays clear
            // for the actual factory. Determinism matters as much here as in FloorTileVariant:
            // a random scatter would rewrite the scene file on every regeneration.
            int count = 0;
            int he = FloorLayout.HalfExtent;
            for (int i = -he + 1; i <= he - 1; i++)
            {
                if (Mod(i * 3, 7) < 2)
                {
                    count += PlaceProp(propsParent, converter, new Vector2Int(he, i),
                        Mod(i, 2) == 0 ? crate : barrel, shadow, expected);
                }
                if (Mod(i * 5 + 2, 7) < 2)
                {
                    count += PlaceProp(propsParent, converter, new Vector2Int(i, he),
                        Mod(i, 2) == 0 ? barrel : crate, shadow, expected);
                }
                if (Mod(i * 3 + 4, 9) < 2)
                {
                    count += PlaceProp(propsParent, converter, new Vector2Int(-he, i),
                        Mod(i, 2) == 0 ? crate : barrel, shadow, expected);
                }
                if (Mod(i * 7 + 1, 9) < 2)
                {
                    count += PlaceProp(propsParent, converter, new Vector2Int(i, -he),
                        Mod(i, 2) == 0 ? barrel : crate, shadow, expected);
                }
            }

            // STREET CLUTTER. Same deterministic-modulo idiom, and needed for the same reason the
            // room has any: seen in Play mode the road's southern half was a hundred blank
            // cobbles, because the five stalls all stand on one row and nothing else is out
            // there. A market with nothing stacked in it does not read as a market.
            //
            // Confined to the two southernmost rows and the side walls beside them. That is the
            // emptiest part of the road AND the part that is provably clear of the stalls: they
            // stand four rows north of here, so the approach tiles §3.2's two-extractor cap needs
            // stay open without this having to know where ProgressionSceneAuthoring put them. A
            // barrel on an approach tile would silently halve a stall's throughput the day
            // extractors start queueing, and nothing would point at the barrel.
            int kerbRow = -he - FloorLayout.StreetDepth;
            for (int x = -he + 1; x <= he - 1; x++)
            {
                if (Mod(x * 5 + 3, 8) < 2)
                {
                    count += PlaceProp(propsParent, converter, new Vector2Int(x, kerbRow),
                        Mod(x, 2) == 0 ? barrel : crate, shadow, expected);
                }
                if (Mod(x * 3 + 5, 11) < 2)
                {
                    count += PlaceProp(propsParent, converter, new Vector2Int(x, kerbRow + 1),
                        Mod(x, 2) == 0 ? crate : barrel, shadow, expected);
                }
            }

            for (int y = kerbRow; y <= kerbRow + 2; y++)
            {
                if (Mod(y * 5 + 1, 3) < 2)
                {
                    count += PlaceProp(propsParent, converter, new Vector2Int(he, y),
                        Mod(y, 2) == 0 ? crate : barrel, shadow, expected);
                }
                if (Mod(y * 7 + 3, 3) < 2)
                {
                    count += PlaceProp(propsParent, converter, new Vector2Int(-he, y),
                        Mod(y, 2) == 0 ? barrel : crate, shadow, expected);
                }
            }

            PruneUnexpected(propsParent, expected);
            return count;
        }

        private static int PlaceProp(Transform parent, GridCoordinateConverter converter,
            Vector2Int cell, Sprite sprite, Sprite shadowSprite, HashSet<string> expected)
        {
            string name = "Prop_" + cell.x + "_" + cell.y;
            Vector3 world = converter.CellToWorldCenter(cell);
            GameObject prop = EnsureSpriteObject(parent, name, sprite, world);
            expected.Add(name);

            // Ensure, not AddComponent: a second run would otherwise stack a second GroundShadow
            // on every prop. GroundShadow.Configure then finds its own existing child by name and
            // reuses it, so the shadow does not multiply either.
            var shadow = Ensure<GroundShadow>(prop);
            shadow.Configure(shadowSprite, Vector2.zero, 0.95f, 0.9f, anchorToBottom: false);
            shadow.Refresh();
            return 1;
        }

        // Sorting order is baked here rather than by adding a YSortSpriteRenderer: none of these
        // pieces ever move, so a per-frame LateUpdate on ~120 static objects would buy nothing,
        // and baking means they also sort correctly in EditMode (YSortSpriteRenderer, like every
        // other gameplay MonoBehaviour here, has no [ExecuteAlways]). The value is exactly what
        // YSortSpriteRenderer would compute, so walls, props, golems and the player all share
        // one depth ordering.
        private static GameObject EnsureSpriteObject(
            Transform parent, string name, Sprite sprite, Vector3 world, int sortingBias = 0)
        {
            GameObject go = EnsureChild(parent, name).gameObject;
            go.transform.position = world;

            var renderer = Ensure<SpriteRenderer>(go);
            renderer.sprite = sprite;
            renderer.sortingOrder = YSortUtility.ComputeSortingOrder(world.y) + sortingBias;

            var litMaterial = AssetDatabase.LoadAssetAtPath<Material>(LitSpriteMaterialPath);
            if (litMaterial != null)
            {
                renderer.sharedMaterial = litMaterial;
            }
            return go;
        }

        private static void EnsureSconceLight(Transform wallSegment, bool lit)
        {
            if (!lit)
            {
                DestroyChild(wallSegment, "SconceLight");
                return;
            }

            Transform lightTransform = EnsureChild(wallSegment, "SconceLight");
            lightTransform.localPosition = new Vector3(0f, LampLightInset, 0f);

            var light = Ensure<Light2D>(lightTransform.gameObject);
            light.lightType = Light2D.LightType.Point;
            light.color = LampColor;
            // Retuned for top-down, where the radii mean something different and there is one
            // lit run instead of two. A world unit used to be one cell across but TWO cells
            // deep (the 1 x 0.5 iso cell), so radius 3 reached 3 cells sideways and 6 back;
            // now it reaches 3 cells in both, over a 25-cell room lit from a single edge. The
            // spacing is 4 cells, so the outer radius has to exceed that or the wall alternates
            // pool-dark-pool instead of reading as continuously lit.
            //
            // RAISED FOR THE DRAMATIC-LIGHTING PASS, together with the global light being cut
            // (see TuneGlobalLight). The two numbers only mean anything as a ratio: at the old
            // 0.95 sconce over a 1.15 ambient, a lit spot was (1.15 + 0.95) / 1.15 = 1.8x the
            // shadow, which is a room lit evenly with faint warm patches -- the "even rather
            // than dramatic" the backlog recorded. At 1.5 over 0.62 it is 3.4x, which is a pool
            // of light with darkness between, and it is the RATIO that does that rather than
            // either number alone.
            light.intensity = SconceIntensity;
            light.pointLightInnerRadius = 0.5f;
            // Widened with the intensity so the pools still overlap: the lamps sit 4 cells
            // apart, and an outer radius that does not exceed the spacing gives a wall that
            // alternates pool-dark-pool, which is exactly what the note above warns against.
            // The brighter a light is, the more visible its own edge becomes.
            light.pointLightOuterRadius = 5.5f;
            light.falloffIntensity = 0.6f;
        }

        /// <summary>
        /// The ambient floor, and the other half of the dramatic-lighting pass.
        ///
        /// <para>
        /// A 2D global light is a flat multiplier over everything, so while it sits near 1 the
        /// sconces can only ever ADD to an already-lit room: nothing is ever in shadow, and the
        /// lamps read as warm patches rather than as the source of the light. Cutting it to
        /// <see cref="GlobalIntensity"/> is what gives the sconces somewhere to be brighter
        /// than -- the same "leave headroom" move the Workbench's hover states needed, and for
        /// the same reason.
        /// </para>
        ///
        /// <para>
        /// <b>0.62 is a floor, not a mood.</b> This is a factory game: the grid, the belts and
        /// the build ghost all have to stay readable in the unlit middle of the room, so the
        /// ambient is cut to roughly half rather than to darkness. Every contrast figure
        /// BuildGhostVisuals measured survives the change, because a uniform multiplier scales
        /// the ghost and the floor it sits on equally and those were all stated as ratios.
        /// </para>
        /// </summary>
        private static void TuneGlobalLight()
        {
            Light2D[] lights = UnityEngine.Object.FindObjectsByType<Light2D>(
                FindObjectsInactive.Include, FindObjectsSortMode.None);

            int tuned = 0;
            for (int i = 0; i < lights.Length; i++)
            {
                if (lights[i].lightType != Light2D.LightType.Global)
                {
                    continue;
                }

                lights[i].intensity = GlobalIntensity;
                EditorUtility.SetDirty(lights[i]);
                tuned++;
            }

            if (tuned == 0)
            {
                Debug.LogWarning("SandboxFloorGenerator: no global Light2D to tune.");
            }
        }

        // Creates the Tile assets on first run so the whole floor is reproducible from the PNGs
        // plus this one menu item, instead of needing a Tile Palette pass that cannot be
        // scripted over the MCP bridge anyway.
        private static TileBase[] LoadOrCreateFloorTiles() =>
            LoadOrCreateTiles(FloorSpriteNames, FloorTileAssetNames);

        // Generalised so the street can have its own tile set without a second copy of the
        // find-or-create dance. Same idempotence rule as the rest of this file: an existing Tile
        // asset is updated in place rather than recreated, so re-running never renumbers a GUID
        // the scene is already referencing.
        private static TileBase[] LoadOrCreateTiles(string[] spriteNames, string[] assetNames)
        {
            var tiles = new TileBase[spriteNames.Length];
            for (int i = 0; i < tiles.Length; i++)
            {
                string tilePath = TileRoot + assetNames[i] + ".asset";
                var tile = AssetDatabase.LoadAssetAtPath<Tile>(tilePath);
                Sprite sprite = LoadSprite(spriteNames[i]);
                if (tile == null)
                {
                    tile = ScriptableObject.CreateInstance<Tile>();
                    tile.sprite = sprite;
                    AssetDatabase.CreateAsset(tile, tilePath);
                }
                else if (tile.sprite != sprite)
                {
                    tile.sprite = sprite;
                    EditorUtility.SetDirty(tile);
                }
                tiles[i] = tile;
            }
            AssetDatabase.SaveAssets();
            return tiles;
        }

        private static Sprite LoadSprite(string spriteName)
        {
            var sprite = AssetDatabase.LoadAssetAtPath<Sprite>(ArtRoot + spriteName + ".png");
            if (sprite == null)
            {
                Debug.LogError("SandboxFloorGenerator: missing sprite " + ArtRoot + spriteName + ".png");
            }
            return sprite;
        }

        // FIND-OR-CREATE, NOT DESTROY-AND-RECREATE, and the reason is the scene diff.
        //
        // Unity mints a fresh fileID for every GameObject and Component it creates, and writes
        // the scene file grouped by those ids. Rebuilding the shell from scratch therefore
        // renumbered ~131 objects and rewrote essentially the whole of Main.unity and
        // Sandbox.unity every single run -- 26,000 changed lines to fix one wall sprite, no way
        // to review what actually moved, and a guaranteed conflict against any other branch that
        // touched the scene. Reusing the object keeps its id, so a run that changes nothing
        // produces a diff that says nothing. CLAUDE.md asks for this of every authoring script;
        // ProgressionSceneAuthoring already did it, and this one was the exception.
        //
        // Names are the identity key, which is why every piece is named from its own coordinates
        // (WallNorth_-12, Prop_7_-12) rather than from a running counter.
        private static Transform EnsureChild(Transform parent, string name)
        {
            Transform existing = parent.Find(name);
            if (existing != null)
            {
                return existing;
            }

            var go = new GameObject(name);
            go.transform.SetParent(parent, worldPositionStays: false);
            return go.transform;
        }

        private static T Ensure<T>(GameObject go) where T : Component
        {
            T component = go.GetComponent<T>();
            return component != null ? component : go.AddComponent<T>();
        }

        // The other half of idempotence: reuse cannot remove. Shrink HalfExtent, or retire a
        // wall run, and the pieces that are no longer generated would otherwise stay in the
        // scene forever with nothing pointing at them.
        private static void PruneUnexpected(Transform parent, HashSet<string> expected)
        {
            for (int i = parent.childCount - 1; i >= 0; i--)
            {
                Transform child = parent.GetChild(i);
                if (!expected.Contains(child.name))
                {
                    Object.DestroyImmediate(child.gameObject);
                }
            }
        }

        private static void DestroyChild(Transform parent, string name)
        {
            Transform existing = parent.Find(name);
            if (existing != null)
            {
                Object.DestroyImmediate(existing.gameObject);
            }
        }

        private static int Mod(int value, int modulus)
        {
            int r = value % modulus;
            return r < 0 ? r + modulus : r;
        }
    }
}
